tasks/config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  get '/auth/beak/callback', to: 'sessions#create'

  resources :tasks do
    collection do
      post :assign
      get :my
    end
    member do
      post :complete
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tasks#index'
end

tasks/app/models/current_account.rb
class CurrentAccount
  attr_reader :id, :email, :role

  def initialize(id:, email:, role:)
    @id = id
    @email = email
    @role = role
  end

  def allowed_to_assign?
    role.to_s == 'manager' || role.to_s == 'admin'
  end
end

tasks/app/models/task.rb
class Task < ApplicationRecord
  enum state: [:open, :done]

  belongs_to :assignee, class_name: 'Account', optional: true

  validates :description, presence: true
end

tasks/app/models/user.rb
# not an AR model!
class User
  attr_reader :id, :name

  def initialize(id, name)
    @id = id
    @name = name
  end

  def self.all
    [
      new('fake_id_1', 'Vasily'),
      new('fake_id_2', 'Elena'),
      new('fake_id_3', 'Konstantin'),
      new('fake_id_4', 'Olga'),
      new('fake_id_5', 'Piotr'),
    ]
  end

  def self.find_by(id:)
    all.detect { |user| user.id == id }
  end
end

tasks/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate

  private

  # Obtain fresh account data from the auth service
  def authenticate
    return redirect_to(login_url) unless session[:token_hash]

    account_data = account_data(session[:token_hash])
    @current_account = CurrentAccount.new(
      id: account_data['id'],
      email: account_data['email'],
      role: account_data['role']
    )
  rescue OAuth2::Error
    session[:token_hash] = nil
    redirect_to login_url
  end

  def current_account
    @current_account
  end
  helper_method :current_account

  def account_data(token_hash)
    client = OmniAuth.strategies.last.new(Rails.application).client
    access_token = OAuth2::AccessToken.from_hash(client, token_hash)

    access_token.get('/accounts/current').parsed
  end
end

tasks/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy complete ]

  def index
    @tasks = Task.open.order(created_at: :desc).includes(:assignee)
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    result, @task = CreateTask.new(attributes: task_params).call

    if result
      redirect_to tasks_url, notice: "Task was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if UpdateTask.new(task: @task, attributes: task_params).call
      redirect_to @task, notice: "Task was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def complete
    CompleteTask.new(task: @task).call
    redirect_to my_tasks_url, notice: "Task marked as done"
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: "Task was successfully destroyed."
  end

  def assign
    AssignOpenTasks.new.call

    redirect_to tasks_url, notice: "All open tasks were assigned"
  end

  def my
    if current_account
      @tasks = FetchUserTasks.new(current_account).call.includes(:assignee)
    else
      redirect_to tasks_url, alert: 'Use user_id query param to authenticate'
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description)
  end
end

tasks/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <br />
    <br />
    <br />

    <hr />

    <h2>Current account</h2>

    <b>Email:</b> <%= current_account.email %>

    <p>
      <%= link_to 'My tasks', my_tasks_path %>
    </p>
    <hr />

    <h2>Actions</h2>

    <% if current_account.allowed_to_assign? %>
      <p>
        <%= link_to 'Assign tasks', assign_tasks_path, method: :post %>
      </p>
    <% end %>

    <p>
      <%= link_to 'Log out', logout_url %>
    </p>
  </body>
</html>

tasks/app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tasks/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

tasks/app/views/tasks/index.html.slim
p#notice= notice
p#alert= alert

h1 Open tasks

- if @tasks.any?
  table
    thead
      tr
        th Description
        th State
        th Assignee
        th(colspan="3")

    tbody
      - @tasks.each do |task|
        tr
          td= task.description
          td= task.state
          td= task.assignee&.email
          td= link_to 'Show', task
          td= link_to 'Edit', edit_task_path(task)
          td= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }
- else
  | No open tasks

br

= link_to 'New Task', new_task_path

tasks/app/views/tasks/my.html.slim
p#notice= notice
p#alert= alert

h1 Tasks

table
  thead
    tr
      th Description
      th State
      th
  tbody
    - @tasks.each do |task|
      tr
        td= task.description
        td= task.state
        td
          - if task.open?
            = link_to "Complete", complete_task_path(task), method: :post

= link_to 'New Task', new_task_path
br
= link_to 'Open tasks', tasks_path

tasks/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

tasks/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Task</h2>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>State:</strong>
  <%= @task.state %>
</p>

<p>
  <strong>Assignee:</strong>
  <%= @task.assignee_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>