accounting/config/routes.rb
Rails.application.routes.draw do
  post 'finish_day/create', as: :finish_day
  resources :balances, only: :show
  root to: 'dashboard#index'

  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  get '/auth/beak/callback', to: 'sessions#create'

  get '/not_authorized' => 'static#not_authorized', as: :not_authorized
end

accounting/app/models/account.rb
class Account < ApplicationRecord
  has_one :balance, dependent: :destroy

  has_many :task_assignments
  has_many :task_completions
end

accounting/app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :account

  has_many :cycles

  def amount
    transactions.map(&:amount).sum
  end

  def transactions
    Transaction.where(cycle_id: cycles.ids)
  end

  def current_cycle
    cycles.order(date: :desc).first
  end
end

accounting/app/models/current_account.rb
class CurrentAccount
  attr_reader :id, :email, :role

  def initialize(id:, email:, role:)
    @id = id
    @email = email
    @role = role
  end

  def allowed_to_access?
    role.to_s == 'accountant' || role.to_s == 'admin'
  end
end

accounting/app/models/cycle.rb
class Cycle < ApplicationRecord
  enum state: [:open, :closed]

  belongs_to :balance

  has_many :transactions

  def self.date_of_cyrrent_cycle
    Cycle.open.pluck(:date).max
  end

  def self.date_of_next_cycle
    date_of_cyrrent_cycle + 1.day
  end

  def total
    transactions.map(&:amount).sum
  end
end

accounting/app/models/payment_transaction.rb
class PaymentTransaction < Transaction
end

accounting/app/models/task_assigned_transaction.rb
class TaskAssignedTransaction < Transaction
  belongs_to :task_assignment
end

accounting/app/models/task_assignment.rb
class TaskAssignment < ApplicationRecord
  belongs_to :account
end

accounting/app/models/task_completed_transaction.rb
class TaskCompletedTransaction < Transaction
  belongs_to :task_completion
end

accounting/app/models/task_completion.rb
class TaskCompletion < ApplicationRecord
  belongs_to :account
end

accounting/app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :cycle

  scope :non_payments, -> { where.not(type: PaymentTransaction.name) }
end

accounting/app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  def show
    @balance = Balance.find(params[:id])
    @transactions = @balance.transactions
    @earned_today = CalcEarnedToday.new(@balance).call

    preload_transaction_associations
  end

  private

  def preload_transaction_associations
    preloader = ActiveRecord::Associations::Preloader.new

    preloader.preload(
      @transactions.select { |t| t.is_a?(TaskAssignedTransaction) }, :task_assignment
    )

    preloader.preload(
      @transactions.select { |t| t.is_a?(TaskCompletedTransaction) }, :task_completion
    )
  end
end

accounting/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @accounts = Account.all.includes(:balance)
    @earned_by_dates = fetch_earnings
  end

  private

  def fetch_earnings
    current_day = Cycle.date_of_cyrrent_cycle
    week_ago = current_day - 7.days

    hash = {}
    (week_ago .. current_day).each do |date|
      hash[date] = CalcCompanyEarnings.new(date).call
    end
    hash
  end
end

accounting/app/controllers/finish_day_controller.rb
class FinishDayController < ApplicationController
  def create
    FinishDay.new.call
    redirect_to root_url, notice: 'Day has passed'
  end
end

accounting/app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_action :authorize

  def not_authorized
  end
end

accounting/app/helpers/balances_helper.rb
module BalancesHelper
  def balance_link(balance)
    link_to formatted_amount(balance.amount), balance_path(balance)
  end

  def formatted_amount(amount)
    as_float = (amount.to_f / 100).round(2)
    "#{as_float}$"
  end
end

accounting/app/helpers/dashboard_helper.rb
module DashboardHelper
end

accounting/app/helpers/finish_day_helper.rb
module FinishDayHelper
end

accounting/app/views/balances/show.html.slim
h1= "Balance of #{@balance.account.email}"

p
  strong Current amount:
  = formatted_amount(@balance.amount)

p
  strong Earned today:
  = formatted_amount(@earned_today)

h3 Transactions

table
  tr
    th Transaction type
    th Amount
    th Description

  - @transactions.each do |transaction|
    tr
      td= transaction.type
      td= formatted_amount(transaction.amount)
      td
        - case transaction
        - when TaskAssignedTransaction
          strong Task description:
          | &nbsp;
          = transaction.task_assignment.task_description
        - when TaskCompletedTransaction
          strong Task description:
          | &nbsp;
          = transaction.task_completion.task_description

br /
= link_to 'Balances', root_path

accounting/app/views/dashboard/index.html.slim
h1 Dashboard

h2 Balances

table
  tr
    th Account email
    th Current balance

  - @accounts.each do |account|
    tr
      td= account.email
      td= balance_link(account.balance)

hr

h2 Earnings

table
  tr
    th Date
    th Earned
  - @earned_by_dates.each do |date, earned|
    tr
      td= date
      td= formatted_amount(earned)


hr

p
  = link_to 'Finish day', finish_day_path, method: :post

accounting/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accounting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <p id=notice><%= notice %></p>
    <p id=alert=><%= alert %></p>
    <%= yield %>
  </body>
</html>